services:
    db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        container_name: "mysql_db"
        restart: always
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks: 
            - sf

    web:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
        restart: always
        container_name: "php_web"
        volumes: 
            - ./src:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - 8080:80
        depends_on: 
            - db
        networks: 
            - sf
    
    phpmyadmin:
        image: phpmyadmin:5.2.1
        restart: always
        ports:
            - 80:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        networks: 
            - sf

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: always
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - sf
volumes:
    db_data:
        driver: local

networks:
    sf: 
        driver: bridge